using TianShu.Contracts.Primitives;

namespace TianShu.Contracts.Workflows;

/// <summary>
/// 控制平面创建批处理作业命令。
/// Control-plane command that creates a batch-oriented job.
/// </summary>
public sealed record ControlPlaneCreateJobCommand
{
    /// <summary>
    /// 作业标识；为空时由执行侧生成。
    /// Job identifier; generated by the execution side when omitted.
    /// </summary>
    public JobId? JobId { get; init; }

    /// <summary>
    /// 作业显示名称。
    /// Human-readable job name.
    /// </summary>
    public string? Name { get; init; }

    /// <summary>
    /// 作业总指令。
    /// High-level instruction for the job.
    /// </summary>
    public string Instruction { get; init; } = string.Empty;

    /// <summary>
    /// 输入表头或字段映射。
    /// Input header or field mapping.
    /// </summary>
    public StructuredValue? InputHeaders { get; init; }

    /// <summary>
    /// 输入 CSV 路径。
    /// Input CSV path.
    /// </summary>
    public string? InputCsvPath { get; init; }

    /// <summary>
    /// 输出 CSV 路径。
    /// Output CSV path.
    /// </summary>
    public string? OutputCsvPath { get; init; }

    /// <summary>
    /// 是否在执行后自动导出。
    /// Whether to auto-export after execution.
    /// </summary>
    public bool? AutoExport { get; init; }

    /// <summary>
    /// 输出结构约束。
    /// Output schema constraint.
    /// </summary>
    public StructuredValue? OutputSchema { get; init; }

    /// <summary>
    /// 待处理条目集合。
    /// Collection of items to be processed.
    /// </summary>
    public IReadOnlyList<StructuredValue> Items { get; init; } = Array.Empty<StructuredValue>();
}

/// <summary>
/// 控制平面派发作业命令。
/// Control-plane command that dispatches a job to target threads.
/// </summary>
public sealed record ControlPlaneDispatchJobCommand
{
    /// <summary>
    /// 待派发的作业标识。
    /// Identifier of the job to dispatch.
    /// </summary>
    public JobId JobId { get; init; }

    /// <summary>
    /// 目标线程列表。
    /// Target thread list.
    /// </summary>
    public IReadOnlyList<ThreadId> ThreadIds { get; init; } = Array.Empty<ThreadId>();
}

/// <summary>
/// 控制平面回报作业条目结果命令。
/// Control-plane command that reports a job-item result.
/// </summary>
public sealed record ControlPlaneReportJobItemCommand
{
    /// <summary>
    /// 作业标识。
    /// Job identifier.
    /// </summary>
    public JobId JobId { get; init; }

    /// <summary>
    /// 条目标识。
    /// Job-item identifier.
    /// </summary>
    public JobItemId ItemId { get; init; }

    /// <summary>
    /// 条目状态。
    /// Job-item status.
    /// </summary>
    public string Status { get; init; } = string.Empty;

    /// <summary>
    /// 条目结果载荷。
    /// Job-item result payload.
    /// </summary>
    public StructuredValue? Result { get; init; }

    /// <summary>
    /// 最近一次错误描述。
    /// Most recent error description.
    /// </summary>
    public string? LastError { get; init; }
}
